/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppConversasRouteImport } from './routes/app.conversas'
import { Route as AppAssistenteRouteImport } from './routes/app.assistente'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppConfiguracoesUsuariosRouteImport } from './routes/app.configuracoes.usuarios'
import { Route as AppConfiguracoesEtiquetasRouteImport } from './routes/app.configuracoes.etiquetas'
import { Route as AppConfiguracoesConhecimentoRouteImport } from './routes/app.configuracoes.conhecimento'
import { Route as AppConfiguracoesClientesRouteImport } from './routes/app.configuracoes.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConversasRoute = AppConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesUsuariosRoute =
  AppConfiguracoesUsuariosRouteImport.update({
    id: '/configuracoes/usuarios',
    path: '/configuracoes/usuarios',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesEtiquetasRoute =
  AppConfiguracoesEtiquetasRouteImport.update({
    id: '/configuracoes/etiquetas',
    path: '/configuracoes/etiquetas',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesConhecimentoRoute =
  AppConfiguracoesConhecimentoRouteImport.update({
    id: '/configuracoes/conhecimento',
    path: '/configuracoes/conhecimento',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesClientesRoute =
  AppConfiguracoesClientesRouteImport.update({
    id: '/configuracoes/clientes',
    path: '/configuracoes/clientes',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/': typeof AppIndexRoute
  '/app/configuracoes/clientes': typeof AppConfiguracoesClientesRoute
  '/app/configuracoes/conhecimento': typeof AppConfiguracoesConhecimentoRoute
  '/app/configuracoes/etiquetas': typeof AppConfiguracoesEtiquetasRoute
  '/app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/conversas': typeof AppConversasRoute
  '/app': typeof AppIndexRoute
  '/app/configuracoes/clientes': typeof AppConfiguracoesClientesRoute
  '/app/configuracoes/conhecimento': typeof AppConfiguracoesConhecimentoRoute
  '/app/configuracoes/etiquetas': typeof AppConfiguracoesEtiquetasRoute
  '/app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/assistente': typeof AppAssistenteRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/': typeof AppIndexRoute
  '/app/configuracoes/clientes': typeof AppConfiguracoesClientesRoute
  '/app/configuracoes/conhecimento': typeof AppConfiguracoesConhecimentoRoute
  '/app/configuracoes/etiquetas': typeof AppConfiguracoesEtiquetasRoute
  '/app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/assistente'
    | '/app/conversas'
    | '/app/'
    | '/app/configuracoes/clientes'
    | '/app/configuracoes/conhecimento'
    | '/app/configuracoes/etiquetas'
    | '/app/configuracoes/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/assistente'
    | '/app/conversas'
    | '/app'
    | '/app/configuracoes/clientes'
    | '/app/configuracoes/conhecimento'
    | '/app/configuracoes/etiquetas'
    | '/app/configuracoes/usuarios'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/agenda'
    | '/app/assistente'
    | '/app/conversas'
    | '/app/'
    | '/app/configuracoes/clientes'
    | '/app/configuracoes/conhecimento'
    | '/app/configuracoes/etiquetas'
    | '/app/configuracoes/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversas': {
      id: '/app/conversas'
      path: '/conversas'
      fullPath: '/app/conversas'
      preLoaderRoute: typeof AppConversasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistente': {
      id: '/app/assistente'
      path: '/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/usuarios': {
      id: '/app/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/app/configuracoes/usuarios'
      preLoaderRoute: typeof AppConfiguracoesUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/etiquetas': {
      id: '/app/configuracoes/etiquetas'
      path: '/configuracoes/etiquetas'
      fullPath: '/app/configuracoes/etiquetas'
      preLoaderRoute: typeof AppConfiguracoesEtiquetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/conhecimento': {
      id: '/app/configuracoes/conhecimento'
      path: '/configuracoes/conhecimento'
      fullPath: '/app/configuracoes/conhecimento'
      preLoaderRoute: typeof AppConfiguracoesConhecimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/clientes': {
      id: '/app/configuracoes/clientes'
      path: '/configuracoes/clientes'
      fullPath: '/app/configuracoes/clientes'
      preLoaderRoute: typeof AppConfiguracoesClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppConversasRoute: typeof AppConversasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfiguracoesClientesRoute: typeof AppConfiguracoesClientesRoute
  AppConfiguracoesConhecimentoRoute: typeof AppConfiguracoesConhecimentoRoute
  AppConfiguracoesEtiquetasRoute: typeof AppConfiguracoesEtiquetasRoute
  AppConfiguracoesUsuariosRoute: typeof AppConfiguracoesUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAssistenteRoute: AppAssistenteRoute,
  AppConversasRoute: AppConversasRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfiguracoesClientesRoute: AppConfiguracoesClientesRoute,
  AppConfiguracoesConhecimentoRoute: AppConfiguracoesConhecimentoRoute,
  AppConfiguracoesEtiquetasRoute: AppConfiguracoesEtiquetasRoute,
  AppConfiguracoesUsuariosRoute: AppConfiguracoesUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
