"""add_clients_appointments_workshop_labels

Revision ID: 65d080f796d0
Revises: 91973c2ec9b2
Create Date: 2026-05-06 22:03:15.524350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d080f796d0'
down_revision: Union[str, None] = '91973c2ec9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_workshop_id'), 'appointments', ['workshop_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('veiculo', sa.String(length=200), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('ultimo_atendimento', sa.String(length=20), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_workshop_id'), 'clients', ['workshop_id'], unique=False)
    op.create_table('workshop_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshop_labels_workshop_id'), 'workshop_labels', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshop_labels_workshop_id'), table_name='workshop_labels')
    op.drop_table('workshop_labels')
    op.drop_index(op.f('ix_clients_workshop_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_appointments_workshop_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
