"""create_conversations_messages_labels

Revision ID: d38521ea7e13
Revises: 
Create Date: 2026-05-06 21:11:56.197744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38521ea7e13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waha_chat_id', sa.String(length=100), nullable=False),
    sa.Column('lead_name', sa.String(length=200), nullable=False),
    sa.Column('lead_phone', sa.String(length=20), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('BOT', 'HUMAN', 'UNASSIGNED', 'RESOLVED', name='conversation_status'), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=100), nullable=True),
    sa.Column('assigned_agent_name', sa.String(length=200), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_waha_chat_id'), 'conversations', ['waha_chat_id'], unique=True)
    op.create_table('conversation_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_labels_conversation_id'), 'conversation_labels', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'DOCUMENT', name='message_type'), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('is_from_lead', sa.Boolean(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('waha_message_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_waha_message_id'), 'messages', ['waha_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_waha_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_labels_conversation_id'), table_name='conversation_labels')
    op.drop_table('conversation_labels')
    op.drop_index(op.f('ix_conversations_waha_chat_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
